'use client'

import { useMemo, useState } from 'react'
import { Check, Download, Eye, FileText, LoaderCircle, Mail, Printer, Send, X } from 'lucide-react'
import { PageHeader } from '@/components/ui/page-header'
import { Button } from '@/components/ui/button'
import { useAuth } from '@/components/auth/auth-provider'
import { useToast } from '@/components/ui/toast-provider'

type Field = { key: string; label: string; placeholder?: string; multiline?: boolean; defaultValue?: string }
type Template = { key: string; title: string; short: string; description: string; fields: Field[]; compensation?: boolean }
type SalaryRow = { label: string; existing: string; revised: string }

const TEMPLATES: Template[] = [
  { key: 'offer', title: 'Offer Letter', short: 'Offer', description: 'One-page branded offer letter based on the approved Aromazen PDF.', fields: [
    { key: 'issue_date', label: 'Issue date', placeholder: 'DD/MM/YYYY' }, { key: 'employee_name', label: 'Candidate name' }, { key: 'interview_date', label: 'Interview date', placeholder: 'DD/MM/YYYY' }, { key: 'designation', label: 'Designation' }, { key: 'joining_date', label: 'Date of joining', placeholder: 'DD/MM/YYYY' }, { key: 'signatory_name', label: 'Authorized signatory' },
  ] },
  { key: 'appointment', title: 'Appointment Letter', short: 'Appointment', description: 'Approved 10-page bilingual appointment terms with compensation annexure.', compensation: true, fields: [
    { key: 'reference_number', label: 'Appointment reference number', placeholder: 'APL/MG/...' }, { key: 'issue_date', label: 'Issue date', placeholder: 'DD/MM/YYYY' }, { key: 'employee_salutation_name', label: 'Employee name with salutation', placeholder: 'Ms. Employee Name' }, { key: 'employee_name', label: 'Employee name without salutation' }, { key: 'employee_name_kannada', label: 'Employee name in Kannada' }, { key: 'employee_address', label: 'Postal address', multiline: true }, { key: 'employee_phone', label: 'Phone number' }, { key: 'designation', label: 'Designation' }, { key: 'designation_kannada', label: 'Designation in Kannada' }, { key: 'joining_date', label: 'Joining date', placeholder: 'DD/MM/YYYY' }, { key: 'reporting_officer', label: 'Reporting officer' }, { key: 'reporting_officer_kannada', label: 'Reporting officer in Kannada' }, { key: 'gross_salary', label: 'Gross monthly salary', placeholder: '33,500/-' }, { key: 'gross_salary_words', label: 'Gross salary in words' }, { key: 'gross_salary_words_kannada', label: 'Gross salary words in Kannada' }, { key: 'signatory_name', label: 'HR signatory name', defaultValue: 'Ms. Swathi Nayak' }, { key: 'signatory_name_kannada', label: 'HR signatory name in Kannada', defaultValue: 'ಸ್ವಾತಿ ನಾಯಕ್' }, { key: 'signatory_title', label: 'Signatory title', defaultValue: 'Human Resources' },
  ] },
  { key: 'spot_appreciation', title: 'Spot Appreciation Letter', short: 'Spot appreciation', description: 'Recognition letter with a custom achievement, impact and optional reward.', fields: [
    { key: 'issue_date', label: 'Issue date', placeholder: 'DD-MM-YYYY' }, { key: 'employee_name', label: 'Employee name with salutation' }, { key: 'designation', label: 'Designation' }, { key: 'appreciation_reason', label: 'What the employee did', multiline: true, defaultValue: 'It gives us great pleasure to appreciate your alertness and proactive approach.' }, { key: 'positive_impact', label: 'Positive impact', multiline: true }, { key: 'reward_statement', label: 'Recognition / reward statement', multiline: true, defaultValue: 'We recognise your initiative and the positive impact of your contribution. As a token of our appreciation, please accept this reward.' }, { key: 'closing_message', label: 'Closing message', multiline: true, defaultValue: 'Thank you for your dedication and good work. Keep up the excellent performance.' }, { key: 'signatory_name', label: 'Signatory name', defaultValue: 'Mrs. Deeksha' }, { key: 'signatory_title', label: 'Signatory title', defaultValue: 'Accounts & HR Head' },
  ] },
  { key: 'special_increment', title: 'Special Increment Letter', short: 'Special increment', description: 'Increment confirmation with existing-versus-revised compensation annexure.', compensation: true, fields: [
    { key: 'issue_date', label: 'Issue date', placeholder: 'DD/MM/YYYY' }, { key: 'employee_name', label: 'Employee name without salutation' }, { key: 'effective_date_long', label: 'Increment effective date', placeholder: '5th August 2026' }, { key: 'revised_gross_salary', label: 'Revised gross monthly salary', placeholder: '₹21,608/-' }, { key: 'appointment_reference', label: 'Appointment letter reference' }, { key: 'appointment_date', label: 'Appointment letter date', placeholder: 'DD/MM/YYYY' }, { key: 'signatory_name', label: 'HR signatory name', defaultValue: 'Ms. Swathi Nayak' }, { key: 'signatory_title', label: 'Signatory title', defaultValue: 'Human Resources' },
  ] },
]

const SALARY_LABELS = ['Basic Salary', 'House Rent Allowance', 'Conveyance Allowance', 'Medical Reimbursement', 'Special Allowance', 'Variable Pay *', '(A) Gross Salary - Total', 'Employer Contribution (PF) @12%', 'Employer Contribution (ESI) @3.25%', '(B) Employee Retiral - Total', 'Residential Telephone Reimbursement*', 'Car fuel and Maintenance Allowance', 'Monthly Perquisites - Total', 'Group Medical Insurance Policy Premium (GMC)', 'Group Personal Accident Policy (GPA)', 'Employee Benefits- Total', 'Fixed Compensation in Hand', 'Cost To Company (CTC) Per Annum -Total', 'Mobile Limit (Per Month)']
const salaryKey = (label: string) => label.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 48)

function LetterFields({ items, values, onChange }: { items: Field[]; values: Record<string, string>; onChange: (key: string, value: string) => void }) {
  return <>{items.map((field) => <label key={field.key} className={field.multiline ? 'md:col-span-2' : ''}><span className="mb-1.5 block text-xs text-muted-foreground">{field.label}</span>{field.multiline ? <textarea rows={3} value={values[field.key]} placeholder={field.placeholder} onChange={(event) => onChange(field.key, event.target.value)} className="w-full rounded-xl border border-border bg-background p-3 text-sm" /> : <input value={values[field.key]} placeholder={field.placeholder} onChange={(event) => onChange(field.key, event.target.value)} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" />}</label>)}</>
}

export function HrLettersTool() {
  const { accessToken } = useAuth(); const { notify } = useToast()
  const [templateKey, setTemplateKey] = useState('offer'); const template = TEMPLATES.find((item) => item.key === templateKey) ?? TEMPLATES[0]
  const [values, setValues] = useState<Record<string, string>>({}); const [salaryRows, setSalaryRows] = useState<SalaryRow[]>(SALARY_LABELS.map((label) => ({ label, existing: '', revised: '' })))
  const [busy, setBusy] = useState(false); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [showEmail, setShowEmail] = useState(false); const [email, setEmail] = useState({ recipient: '', subject: '', message: '' }); const [sending, setSending] = useState(false)
  const fields = useMemo(() => Object.fromEntries(template.fields.map((field) => [field.key, values[`${template.key}:${field.key}`] ?? field.defaultValue ?? ''])), [template, values])
  const payloadFields = useMemo(() => ({ ...fields, ...Object.fromEntries(salaryRows.flatMap((row) => [[`salary_${salaryKey(row.label)}_existing`, row.existing], [`salary_${salaryKey(row.label)}_revised`, row.revised]])) }), [fields, salaryRows])
  function change(key: string, value: string) { setValues((current) => ({ ...current, [`${template.key}:${key}`]: value })); setPreviewUrl((current) => { if (current) URL.revokeObjectURL(current); return null }) }
  function choose(key: string) { setTemplateKey(key); setPreviewUrl((current) => { if (current) URL.revokeObjectURL(current); return null }) }
  async function generatePreview() { if (!accessToken) return; setBusy(true); try { const response = await fetch('/api/v1/hr-letters/preview', { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ template_key: template.key, fields: payloadFields }) }); if (!response.ok) { const error = await response.json().catch(() => null); throw new Error(error?.detail ?? 'Unable to generate this letter.') } const url = URL.createObjectURL(await response.blob()); setPreviewUrl((current) => { if (current) URL.revokeObjectURL(current); return url }); setEmail((current) => ({ ...current, subject: current.subject || `${template.title} - ${fields.employee_name || 'Employee'}`, message: current.message || `Dear ${fields.employee_name || 'Employee'},\n\nPlease find your ${template.title.toLowerCase()} attached.\n\nRegards,\nHuman Resources` })); } catch (error) { notify('error', error instanceof Error ? error.message : 'Unable to generate this letter.') } finally { setBusy(false) } }
  function print() { const frame = document.getElementById('hr-letter-preview') as HTMLIFrameElement | null; frame?.contentWindow?.focus(); frame?.contentWindow?.print() }
  function download() { if (!previewUrl) return; const link = document.createElement('a'); link.href = previewUrl; link.download = `${template.key}-${fields.employee_name || 'employee'}.pdf`; link.click() }
  async function sendEmail() { if (!accessToken || !email.recipient.trim()) return; setSending(true); try { const response = await fetch('/api/v1/hr-letters/send', { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ template_key: template.key, fields: payloadFields, recipient_email: email.recipient, subject: email.subject, message: email.message }) }); if (!response.ok) { const error = await response.json().catch(() => null); throw new Error(error?.detail ?? 'Unable to send this letter.') } notify('success', 'Letter sent successfully through HR Zoho Mail.'); setShowEmail(false) } catch (error) { notify('error', error instanceof Error ? error.message : 'Unable to send this letter.') } finally { setSending(false) } }
  return <main className="space-y-5 p-4 md:p-6"><PageHeader title="Offer / Appointment / Spot Appreciation / Special Increment Letters" description="Choose an approved HR template, enter only its variable details, review the final PDF, then print or email it." />
    <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{TEMPLATES.map((item) => <button key={item.key} onClick={() => choose(item.key)} className={`flex items-center gap-3 rounded-xl border px-4 py-3 text-left transition ${template.key === item.key ? 'border-primary bg-primary/5 ring-1 ring-primary/30' : 'border-border bg-card hover:border-primary/40'}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${template.key === item.key ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{template.key === item.key ? <Check className="h-4 w-4" /> : <FileText className="h-4 w-4" />}</span><p className="text-sm font-semibold">{item.short}</p></button>)}</section>
    <div className={`grid gap-5 ${previewUrl ? 'xl:grid-cols-[minmax(0,1fr)_minmax(440px,.9fr)]' : 'mx-auto w-full max-w-3xl'}`}><div className="space-y-5"><section className="rounded-2xl border border-border bg-card p-4 md:p-5"><div className="mb-5"><p className="text-xs font-medium uppercase tracking-[.14em] text-primary">Step 1 · Enter details</p><h2 className="mt-1 text-lg font-semibold">{template.title}</h2><p className="mt-1 text-xs text-muted-foreground">Approved fixed wording is locked. Only the fields below will change.</p></div><div className="grid gap-4 md:grid-cols-2"><LetterFields items={template.fields.slice(0, 8)} values={fields} onChange={change} />{template.fields.length > 8 && <details className="md:col-span-2 rounded-xl border border-border"><summary className="cursor-pointer p-3 text-sm font-medium">Additional letter details <span className="ml-1 text-xs font-normal text-muted-foreground">{template.fields.length - 8} fields</span></summary><div className="grid gap-4 border-t border-border p-3 md:grid-cols-2"><LetterFields items={template.fields.slice(8)} values={fields} onChange={change} /></div></details>}</div></section>
      {template.compensation && <details className="rounded-2xl border border-border bg-card"><summary className="cursor-pointer p-4 text-sm font-medium">Compensation details <span className="ml-1 text-xs font-normal text-muted-foreground">Open only when needed</span></summary><div className="border-t border-border p-4 md:p-5"><p className="text-xs text-muted-foreground">Enter existing and revised monthly values. Use NIL where a component does not apply.</p><div className="mt-4 max-h-[32rem] overflow-auto rounded-xl border border-border"><table className="w-full min-w-[600px] text-sm"><thead className="sticky top-0 bg-muted"><tr><th className="p-3 text-left">Salary component</th><th className="p-3 text-left">Existing</th><th className="p-3 text-left">Revised</th></tr></thead><tbody>{salaryRows.map((row, index) => <tr key={row.label} className="border-t border-border"><td className="p-3 text-xs">{row.label}</td>{(['existing', 'revised'] as const).map((column) => <td key={column} className="p-2"><input value={row[column]} onChange={(event) => { setSalaryRows((current) => current.map((item, rowIndex) => rowIndex === index ? { ...item, [column]: event.target.value } : item)); setPreviewUrl(null) }} className="h-9 w-full rounded-lg border border-border bg-background px-2 text-sm" placeholder="NIL" /></td>)}</tr>)}</tbody></table></div></div></details>}
      <section className="flex justify-end rounded-2xl border border-border bg-card p-4"><Button onClick={() => void generatePreview()} disabled={busy}>{busy ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Eye className="mr-2 h-4 w-4" />}{busy ? 'Preparing review' : 'Review final letter'}</Button></section></div>
      {previewUrl && <section className="sticky top-4 h-fit overflow-hidden rounded-2xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div><p className="text-xs font-medium uppercase tracking-[.14em] text-primary">Step 2 · Review</p><h2 className="mt-1 font-semibold">Final print preview</h2></div>{previewUrl && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={download}><Download className="mr-1.5 h-4 w-4" />PDF</Button><Button size="sm" variant="outline" onClick={print}><Printer className="mr-1.5 h-4 w-4" />Print</Button><Button size="sm" onClick={() => setShowEmail(true)}><Mail className="mr-1.5 h-4 w-4" />Email</Button></div>}</div>{previewUrl ? <iframe id="hr-letter-preview" title="Letter preview" src={previewUrl} className="h-[72vh] w-full bg-white" /> : <div className="grid h-[64vh] place-items-center p-8 text-center"><div><FileText className="mx-auto h-10 w-10 text-muted-foreground" /><p className="mt-3 font-medium">Your reviewed letter appears here</p><p className="mt-1 max-w-sm text-sm leading-6 text-muted-foreground">Complete the fields and select Review final letter. Printing and email are enabled only after review.</p></div></div>}</section>}</div>
    {showEmail && <div className="fixed inset-0 z-50 grid place-items-center bg-black/65 p-4 backdrop-blur-sm"><div className="w-full max-w-lg rounded-2xl border border-border bg-card p-5 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-medium uppercase tracking-[.14em] text-primary">Step 3 · Send</p><h2 className="mt-1 text-lg font-semibold">Email reviewed PDF</h2></div><button onClick={() => setShowEmail(false)}><X className="h-4 w-4" /></button></div><div className="mt-5 space-y-3"><label><span className="mb-1 block text-xs text-muted-foreground">Recipient email</span><input type="email" value={email.recipient} onChange={(event) => setEmail((current) => ({ ...current, recipient: event.target.value }))} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" /></label><label><span className="mb-1 block text-xs text-muted-foreground">Subject</span><input value={email.subject} onChange={(event) => setEmail((current) => ({ ...current, subject: event.target.value }))} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" /></label><label><span className="mb-1 block text-xs text-muted-foreground">Email message</span><textarea rows={6} value={email.message} onChange={(event) => setEmail((current) => ({ ...current, message: event.target.value }))} className="w-full rounded-xl border border-border bg-background p-3 text-sm" /></label></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setShowEmail(false)} disabled={sending}>Cancel</Button><Button onClick={() => void sendEmail()} disabled={sending || !email.recipient || !email.subject || !email.message}>{sending ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}{sending ? 'Sending' : 'Send with PDF'}</Button></div></div></div>}
  </main>
}
