'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { Building2, Check, Copy, Download, ExternalLink, Eye, FileText, Languages, LoaderCircle, Mail, Printer, Send, Upload, X } from 'lucide-react'
import { PageHeader } from '@/components/ui/page-header'
import { Button } from '@/components/ui/button'
import { useAuth } from '@/components/auth/auth-provider'
import { useToast } from '@/components/ui/toast-provider'
import { api } from '@/lib/api/services'
import type { HRTemplate, HRTemplateField } from '@/lib/api/types'
import { ApiError } from '@/lib/api/client'
import { canvaEditUrlForHrLetter } from '@/lib/template-canva-links'

type SalaryColumn = 'existing' | 'revised' | 'monthly' | 'annual'
type UnitNumber = 1 | 2 | 3

const UNIT_OPTIONS: UnitNumber[] = [1, 2, 3]
const UNIT_ADDRESSES: Record<UnitNumber, string> = {
  1: 'Plot No. B 105/106, Baikampady Industrial Area, Mangalore, Dakshina Kannada, Karnataka - 575011',
  2: 'Ground Floor, Plot No. 42 & 43, Kallur, Mandli Kallur Industrial Area, Shivamogga, Karnataka - 577202',
  3: 'Plot 166A, Baikampady Industrial Road Area, Mangalore, Dakshina Kannada, Karnataka - 575011',
}

function LetterFields({ items, values, onChange }: { items: HRTemplateField[]; values: Record<string, string>; onChange: (key: string, value: string) => void }) {
  return <>{items.map((field) => <label key={field.key} className={field.multiline ? 'md:col-span-2' : ''}><span className="mb-1.5 block text-xs text-muted-foreground">{field.label}{field.required ? ' *' : ''}</span>{field.multiline ? <textarea rows={3} value={values[field.key] ?? ''} onChange={(event) => onChange(field.key, event.target.value)} className="w-full rounded-xl border border-border bg-background p-3 text-sm" /> : <input value={values[field.key] ?? ''} onChange={(event) => onChange(field.key, event.target.value)} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" />}</label>)}</>
}

export function HrLettersTool() {
  const { accessToken, hasPermission } = useAuth(); const { notify } = useToast()
  const uploadRef = useRef<HTMLInputElement>(null)
  const [selectedUnit, setSelectedUnit] = useState<UnitNumber>(1)
  const [templates, setTemplates] = useState<HRTemplate[]>([]); const [templateKey, setTemplateKey] = useState('offer')
  const template = templates.find((item) => item.key === templateKey) ?? templates[0]
  const canvaEditUrl = template ? canvaEditUrlForHrLetter(template.key) : null
  const activeKey = template?.key ?? templateKey
  const activeScope = activeKey
  const usesUnitAddress = activeKey === 'offer'
  const [values, setValues] = useState<Record<string, string>>({}); const [salaryValues, setSalaryValues] = useState<Record<string, string>>({})
  const [busy, setBusy] = useState(false); const [previewUrl, setPreviewUrl] = useState<string | null>(null); const [showEmail, setShowEmail] = useState(false); const [email, setEmail] = useState({ recipient: '', subject: '', message: '' }); const [sending, setSending] = useState(false)
  const [replacing, setReplacing] = useState(false)
  const [translatorText, setTranslatorText] = useState(''); const [translation, setTranslation] = useState(''); const [translating, setTranslating] = useState(false)
  useEffect(() => {
    if (!accessToken) return
    let cancelled = false
    void api.hrTemplates.list(accessToken).then((items) => { if (!cancelled) setTemplates(items) }).catch((error) => { if (!cancelled) notify('error', error instanceof ApiError ? error.message : 'Unable to load HR templates.') })
    return () => { cancelled = true }
  }, [accessToken, notify])
  const fields = useMemo(() => Object.fromEntries((template?.fields ?? []).map((field) => [field.key, values[`${activeScope}:${field.key}`] ?? field.default_value ?? ''])), [activeScope, template, values])
  const salaryColumns = useMemo(() => ([
    { key: 'existing' as SalaryColumn, label: 'Existing' }, { key: 'revised' as SalaryColumn, label: 'Revised' },
    { key: 'monthly' as SalaryColumn, label: 'Amount (per month)' }, { key: 'annual' as SalaryColumn, label: 'Amount (per annum)' },
  ]).filter((column) => template?.salary_rows.some((row) => row.columns.includes(column.key))), [template])
  const payloadFields = useMemo(() => ({ ...fields, ...Object.fromEntries((template?.salary_rows ?? []).flatMap((row) => row.columns.map((column) => [
    `salary_${row.key}_${column}`, salaryValues[`${activeScope}:${row.key}:${column}`] ?? '',
  ]))) }), [activeScope, fields, salaryValues, template])
  function clearPreview() { setPreviewUrl((current) => { if (current) URL.revokeObjectURL(current); return null }) }
  function change(key: string, value: string) { if (!template) return; setValues((current) => ({ ...current, [`${activeScope}:${key}`]: value })); clearPreview() }
  function choose(key: string) { setTemplateKey(key); setPreviewUrl((current) => { if (current) URL.revokeObjectURL(current); return null }) }
  function chooseUnit(unit: UnitNumber) { setSelectedUnit(unit); clearPreview() }
  async function viewTemplate() { if (!accessToken || !template) return; try { const file = await api.hrTemplates.content(accessToken, template.key); const url = URL.createObjectURL(file.blob); window.open(url, '_blank', 'noopener,noreferrer'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000) } catch (error) { notify('error', error instanceof ApiError ? error.message : 'Unable to open this template.') } }
  async function replaceTemplate(file: File | null) { if (!accessToken || !template || !file) return; setReplacing(true); try { const next = await api.hrTemplates.replace(accessToken, template.key, file); setTemplates((items) => items.map((item) => item.key === next.key ? next : item)); setValues((current) => Object.fromEntries(Object.entries(current).filter(([key]) => !key.startsWith(`${template.key}:`)))); setPreviewUrl(null); notify('success', `${next.title} master v${next.version} is active for all units and saved in Human Resources Knowledge.`) } catch (error) { notify('error', error instanceof ApiError ? error.message : 'Unable to replace this template.') } finally { setReplacing(false); if (uploadRef.current) uploadRef.current.value = '' } }
  async function generatePreview() { if (!accessToken || !template) return; setBusy(true); try { const response = await fetch('/api/v1/hr-letters/preview', { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ template_key: template.key, unit_number: selectedUnit, fields: payloadFields }) }); if (!response.ok) { const error = await response.json().catch(() => null); throw new Error(error?.detail ?? 'Unable to generate this letter.') } const url = URL.createObjectURL(await response.blob()); setPreviewUrl((current) => { if (current) URL.revokeObjectURL(current); return url }); setEmail((current) => ({ ...current, subject: current.subject || `${template.title} - ${fields.employee_name || 'Employee'}`, message: current.message || `Dear ${fields.employee_name || 'Employee'},\n\nPlease find your ${template.title.toLowerCase()} attached.\n\nRegards,\nHuman Resources` })); } catch (error) { notify('error', error instanceof Error ? error.message : 'Unable to generate this letter.') } finally { setBusy(false) } }
  async function translateToKannada() { if (!accessToken || !translatorText.trim()) return; setTranslating(true); try { const response = await fetch('/api/v1/hr-letters/translate-kannada', { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ text: translatorText.trim() }) }); if (!response.ok) { const error = await response.json().catch(() => null); throw new Error(error?.detail ?? 'Unable to translate this text.') } const result = await response.json(); setTranslation(result.translation ?? '') } catch (error) { notify('error', error instanceof Error ? error.message : 'Unable to translate this text.') } finally { setTranslating(false) } }
  async function copyTranslation() { if (!translation) return; await navigator.clipboard.writeText(translation); notify('success', 'Kannada translation copied. Paste it into the relevant Kannada field.') }
  function print() { const frame = document.getElementById('hr-letter-preview') as HTMLIFrameElement | null; frame?.contentWindow?.focus(); frame?.contentWindow?.print() }
  function download() { if (!previewUrl || !template) return; const link = document.createElement('a'); link.href = previewUrl; const unitPart = usesUnitAddress ? `-unit-${selectedUnit}` : ''; link.download = `${template.key}${unitPart}-${fields.employee_name || 'employee'}.pdf`; link.click() }
  async function sendEmail() { if (!accessToken || !template || !email.recipient.trim()) return; setSending(true); try { const response = await fetch('/api/v1/hr-letters/send', { method: 'POST', headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ template_key: template.key, unit_number: selectedUnit, fields: payloadFields, recipient_email: email.recipient, subject: email.subject, message: email.message }) }); if (!response.ok) { const error = await response.json().catch(() => null); throw new Error(error?.detail ?? 'Unable to send this letter.') } notify('success', `${usesUnitAddress ? `Unit ${selectedUnit} ` : ''}${template.title} sent successfully through HR Zoho Mail.`); setShowEmail(false) } catch (error) { notify('error', error instanceof Error ? error.message : 'Unable to send this letter.') } finally { setSending(false) } }
  if (!template) return <main className="grid min-h-[50vh] place-items-center"><LoaderCircle className="h-6 w-6 animate-spin text-primary" /></main>
  return <main className="space-y-5 p-4 md:p-6"><PageHeader title="HR Letter Templates" description="Offer Letters use the selected unit address. Appointment, Spot Appreciation and Special Increment letters are formatted for printing on official letterhead." />
    {usesUnitAddress && <section className="flex flex-col gap-4 rounded-2xl border border-border bg-card p-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Building2 className="h-5 w-5" /></span><div><h2 className="font-semibold">Choose company unit</h2><p className="mt-1 text-xs text-muted-foreground">The selected unit controls the address used in the Offer Letter preview, PDF and email attachment.</p><p className="mt-2 max-w-2xl text-sm leading-5">{UNIT_ADDRESSES[selectedUnit]}</p></div></div><label className="w-full shrink-0 sm:w-52"><span className="sr-only">Company unit</span><select value={selectedUnit} onChange={(event) => chooseUnit(Number(event.target.value) as UnitNumber)} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm font-medium">{UNIT_OPTIONS.map((unit) => <option key={unit} value={unit}>Unit {unit}</option>)}</select></label></section>}
    <section className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{templates.map((item) => <button key={item.key} onClick={() => choose(item.key)} className={`flex items-center gap-3 rounded-xl border px-4 py-3 text-left transition ${template.key === item.key ? 'border-primary bg-primary/5 ring-1 ring-primary/30' : 'border-border bg-card hover:border-primary/40'}`}><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg ${template.key === item.key ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground'}`}>{template.key === item.key ? <Check className="h-4 w-4" /> : <FileText className="h-4 w-4" />}</span><div><p className="text-sm font-semibold">{item.short}</p><p className="mt-0.5 text-[11px] text-muted-foreground">v{item.version} · {item.detected_field_count} mapped fields</p></div></button>)}</section>
    <section className="flex flex-col gap-4 rounded-2xl border border-primary/25 bg-primary/5 p-4 md:flex-row md:items-center md:justify-between"><div className="flex min-w-0 items-start gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/15 text-primary"><FileText className="h-5 w-5" /></span><div className="min-w-0"><h2 className="font-semibold">Current {template.title} master</h2><p className="truncate text-sm text-muted-foreground">{template.filename} · Version {template.version} · {template.source === 'knowledge' ? 'Human Resources Knowledge' : 'Built-in starter'}</p><p className="mt-1 text-xs text-muted-foreground">Every unique {'{{field_name}}'} placeholder automatically becomes a mapped portal field. Offer Letters also map the selected unit address; the other three masters preserve clear space for the pre-printed letterhead on every page.</p></div></div><div className="flex shrink-0 flex-wrap gap-2"><Button variant="outline" onClick={() => void viewTemplate()}><Eye className="mr-2 h-4 w-4" />View template</Button>{hasPermission('knowledge.write') && <>{canvaEditUrl && <Button variant="outline" onClick={() => window.open(canvaEditUrl, '_blank', 'noopener,noreferrer')}><ExternalLink className="mr-2 h-4 w-4" />Edit in Canva</Button>}<input ref={uploadRef} hidden type="file" accept={template.key === 'offer' ? '.pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document' : '.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document'} onChange={(event) => void replaceTemplate(event.target.files?.[0] ?? null)} /><Button disabled={replacing} onClick={() => uploadRef.current?.click()}>{replacing ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Upload className="mr-2 h-4 w-4" />}{replacing ? 'Mapping fields' : 'Upload master template'}</Button></>}</div></section>
    {template.fields.some((field) => field.key.endsWith('_kannada')) && <section className="rounded-2xl border border-primary/25 bg-primary/5 p-4 md:p-5"><div className="flex items-start gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground"><Languages className="h-4 w-4" /></span><div><h2 className="font-semibold">Kannada translation helper</h2><p className="mt-1 text-xs leading-5 text-muted-foreground">Translate text, then paste the result into the matching Kannada field detected from this template.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-2"><textarea rows={3} value={translatorText} onChange={(event) => setTranslatorText(event.target.value)} placeholder="Enter English text" className="w-full rounded-xl border border-border bg-background p-3 text-sm" /><textarea rows={3} value={translation} readOnly placeholder="Kannada translation appears here" className="w-full rounded-xl border border-border bg-background p-3 text-sm" /></div><div className="mt-3 flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => void copyTranslation()} disabled={!translation}><Copy className="mr-1.5 h-4 w-4" />Copy Kannada</Button><Button type="button" onClick={() => void translateToKannada()} disabled={translating || !translatorText.trim()}>{translating ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Languages className="mr-2 h-4 w-4" />}{translating ? 'Translating' : 'Translate to Kannada'}</Button></div></section>}
    <div className={`grid gap-5 ${previewUrl ? 'xl:grid-cols-[minmax(0,1fr)_minmax(440px,.9fr)]' : 'mx-auto w-full max-w-3xl'}`}><div className="space-y-5"><section className="rounded-2xl border border-border bg-card p-4 md:p-5"><div className="mb-5"><p className="text-xs font-medium uppercase tracking-[.14em] text-primary">Step 1 · Enter details</p><h2 className="mt-1 text-lg font-semibold">{template.title}</h2><p className="mt-1 text-xs text-muted-foreground">Approved fixed wording is locked. Only the fields below will change.</p></div><div className="grid gap-4 md:grid-cols-2"><LetterFields items={template.fields.slice(0, 8)} values={fields} onChange={change} />{template.fields.length > 8 && <details className="md:col-span-2 rounded-xl border border-border"><summary className="cursor-pointer p-3 text-sm font-medium">Additional letter details <span className="ml-1 text-xs font-normal text-muted-foreground">{template.fields.length - 8} fields</span></summary><div className="grid gap-4 border-t border-border p-3 md:grid-cols-2"><LetterFields items={template.fields.slice(8)} values={fields} onChange={change} /></div></details>}</div></section>
      {template.salary_rows.length > 0 && <details className="rounded-2xl border border-border bg-card"><summary className="cursor-pointer p-4 text-sm font-medium">Compensation details <span className="ml-1 text-xs font-normal text-muted-foreground">{template.salary_rows.length} rows detected from template</span></summary><div className="border-t border-border p-4 md:p-5"><p className="text-xs text-muted-foreground">The rows and columns below come directly from placeholders in the active template. Blank cells print as NIL.</p><div className="mt-4 max-h-[32rem] overflow-auto rounded-xl border border-border"><table className="w-full min-w-[600px] text-sm"><thead className="sticky top-0 bg-muted"><tr><th className="p-3 text-left">Salary component</th>{salaryColumns.map((column) => <th key={column.key} className="p-3 text-left">{column.label}</th>)}</tr></thead><tbody>{template.salary_rows.map((row) => <tr key={row.key} className="border-t border-border"><td className="p-3 text-xs">{row.label}</td>{salaryColumns.map((column) => <td key={column.key} className="p-2">{row.columns.includes(column.key) ? <input value={salaryValues[`${activeScope}:${row.key}:${column.key}`] ?? ''} onChange={(event) => { setSalaryValues((current) => ({ ...current, [`${activeScope}:${row.key}:${column.key}`]: event.target.value })); clearPreview() }} className="h-9 w-full rounded-lg border border-border bg-background px-2 text-sm" placeholder="NIL when blank" /> : <span className="block text-center text-muted-foreground">—</span>}</td>)}</tr>)}</tbody></table></div></div></details>}
      <section className="flex justify-end rounded-2xl border border-border bg-card p-4"><Button onClick={() => void generatePreview()} disabled={busy}>{busy ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Eye className="mr-2 h-4 w-4" />}{busy ? 'Preparing review' : 'Review final letter'}</Button></section></div>
      {previewUrl && <section className="sticky top-4 h-fit overflow-hidden rounded-2xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div><p className="text-xs font-medium uppercase tracking-[.14em] text-primary">Step 2 · Review</p><h2 className="mt-1 font-semibold">Final print preview</h2></div>{previewUrl && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={download}><Download className="mr-1.5 h-4 w-4" />PDF</Button><Button size="sm" variant="outline" onClick={print}><Printer className="mr-1.5 h-4 w-4" />Print</Button><Button size="sm" onClick={() => setShowEmail(true)}><Mail className="mr-1.5 h-4 w-4" />Email</Button></div>}</div>{previewUrl ? <iframe id="hr-letter-preview" title="Letter preview" src={previewUrl} className="h-[72vh] w-full bg-white" /> : <div className="grid h-[64vh] place-items-center p-8 text-center"><div><FileText className="mx-auto h-10 w-10 text-muted-foreground" /><p className="mt-3 font-medium">Your reviewed letter appears here</p><p className="mt-1 max-w-sm text-sm leading-6 text-muted-foreground">Complete the fields and select Review final letter. Printing and email are enabled only after review.</p></div></div>}</section>}</div>
    {showEmail && <div className="fixed inset-0 z-50 grid place-items-center bg-black/65 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Email reviewed PDF"><div className="w-full max-w-lg rounded-2xl border border-border bg-card p-5 shadow-2xl"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-medium uppercase tracking-[.14em] text-primary">Step 3 · Send</p><h2 className="mt-1 text-lg font-semibold">Email reviewed PDF</h2></div><button type="button" onClick={() => setShowEmail(false)} className="shrink-0 rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground" aria-label="Close email dialog"><X className="h-4 w-4" /></button></div><div className="mt-5 space-y-3"><label><span className="mb-1 block text-xs text-muted-foreground">Recipient email</span><input type="email" value={email.recipient} onChange={(event) => setEmail((current) => ({ ...current, recipient: event.target.value }))} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" /></label><label><span className="mb-1 block text-xs text-muted-foreground">Subject</span><input value={email.subject} onChange={(event) => setEmail((current) => ({ ...current, subject: event.target.value }))} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" /></label><label><span className="mb-1 block text-xs text-muted-foreground">Email message</span><textarea rows={6} value={email.message} onChange={(event) => setEmail((current) => ({ ...current, message: event.target.value }))} className="w-full rounded-xl border border-border bg-background p-3 text-sm" /></label></div><div className="mt-5 flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={() => setShowEmail(false)} disabled={sending}>Cancel</Button><Button onClick={() => void sendEmail()} disabled={sending || !email.recipient || !email.subject || !email.message}>{sending ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <Send className="mr-2 h-4 w-4" />}{sending ? 'Sending' : 'Send with PDF'}</Button></div></div></div>}
  </main>
}
