'use client'

import { ChangeEvent, useEffect, useMemo, useRef, useState } from 'react'
import { BookOpenCheck, CheckCircle2, Download, Eye, FileSpreadsheet, FileText, LoaderCircle, Plus, Printer, Search, Trash2 } from 'lucide-react'
import { useParams } from 'next/navigation'
import { AppLayout } from '@/components/layouts/app-layout'
import { PageHeader } from '@/components/ui/page-header'
import { Button } from '@/components/ui/button'
import { useAuth } from '@/components/auth/auth-provider'
import { useToast } from '@/components/ui/toast-provider'
import { api } from '@/lib/api/services'
import type { AttendanceAnalysis, AttendanceShiftRule, KnowledgeCollection, KnowledgeDocument } from '@/lib/api/types'
import { ApiError } from '@/lib/api/client'
import { HrLettersTool } from '@/components/department-tools/hr-letters-tool'
import { HrCustomLettersTool } from '@/components/department-tools/hr-custom-letters-tool'
import { HrInterviewTool } from '@/components/department-tools/hr-interview-tool'
import { QaCoaTool } from '@/components/department-tools/qa-coa-tool'
import { RegulatoryDocumentsTool } from '@/components/department-tools/regulatory-documents-tool'

type Field = { key: string; label: string; placeholder?: string; type?: 'text' | 'date' | 'number' | 'textarea' | 'select'; options?: string[] }
type ToolConfig = { department: 'R&D' | 'HR'; title: string; description: string; fields: Field[]; rowTitle: string; columns: Field[] }

const CONFIGS: Record<string, ToolConfig> = {
  'rnd-formulation': { department: 'R&D', title: 'Formulation and Batch Sheet', description: 'Prepare a controlled formulation, process and batch record.', fields: [
    { key: 'product', label: 'Product / formulation name' }, { key: 'code', label: 'Formula code' }, { key: 'version', label: 'Version' }, { key: 'batch', label: 'Batch number' }, { key: 'date', label: 'Batch date', type: 'date' }, { key: 'target', label: 'Target batch quantity' }, { key: 'prepared', label: 'Prepared by' }, { key: 'checked', label: 'Checked by' }, { key: 'process', label: 'Process instructions', type: 'textarea' }, { key: 'observations', label: 'Batch observations', type: 'textarea' },
  ], rowTitle: 'Formula ingredients', columns: [{ key: 'ingredient', label: 'Ingredient' }, { key: 'code', label: 'Material code' }, { key: 'percentage', label: '%', type: 'number' }, { key: 'quantity', label: 'Quantity' }, { key: 'stage', label: 'Addition stage' }] },
  'rnd-raw-material': { department: 'R&D', title: 'Raw Material Evaluation Report', description: 'Record technical checks and an approval decision for a raw material.', fields: [
    { key: 'material', label: 'Raw material' }, { key: 'code', label: 'Material code' }, { key: 'supplier', label: 'Supplier' }, { key: 'lot', label: 'Lot / batch number' }, { key: 'date', label: 'Evaluation date', type: 'date' }, { key: 'evaluator', label: 'Evaluated by' }, { key: 'use', label: 'Intended use' }, { key: 'decision', label: 'Decision', type: 'select', options: ['Approved', 'Conditionally approved', 'Rejected', 'Further testing required'] }, { key: 'comments', label: 'Conclusion and comments', type: 'textarea' },
  ], rowTitle: 'Evaluation parameters', columns: [{ key: 'parameter', label: 'Parameter' }, { key: 'specification', label: 'Specification' }, { key: 'result', label: 'Observed result' }, { key: 'status', label: 'Status', type: 'select', options: ['Pass', 'Fail', 'Not tested'] }] },
  'hr-letters': { department: 'HR', title: 'Offer / Appointment / Spot Appreciation / Special Increment Letters', description: 'Enter employee details, review the approved letter and print or email it.', fields: [
    { key: 'letter_type', label: 'Letter type', type: 'select', options: ['Offer Letter', 'Appointment Letter'] }, { key: 'date', label: 'Issue date', type: 'date' }, { key: 'employee', label: 'Employee name' }, { key: 'address', label: 'Employee address', type: 'textarea' }, { key: 'designation', label: 'Designation' }, { key: 'department', label: 'Department' }, { key: 'joining', label: 'Joining date', type: 'date' }, { key: 'location', label: 'Work location' }, { key: 'salary', label: 'Annual CTC / salary' }, { key: 'reporting', label: 'Reporting manager' }, { key: 'probation', label: 'Probation period' }, { key: 'terms', label: 'Additional terms', type: 'textarea' }, { key: 'signatory', label: 'Authorized signatory' },
  ], rowTitle: 'Optional compensation components', columns: [{ key: 'component', label: 'Component' }, { key: 'monthly', label: 'Monthly' }, { key: 'annual', label: 'Annual' }] },
  'hr-interview': { department: 'HR', title: 'Interview Parameter Checklist', description: 'Use one consistent scorecard for every candidate interviewed for a role.', fields: [
    { key: 'candidate', label: 'Candidate name' }, { key: 'role', label: 'Position' }, { key: 'department', label: 'Department' }, { key: 'date', label: 'Interview date', type: 'date' }, { key: 'interviewer', label: 'Interviewer(s)' }, { key: 'round', label: 'Interview round' }, { key: 'recommendation', label: 'Final recommendation', type: 'select', options: ['Strong hire', 'Hire', 'Hold', 'No hire'] }, { key: 'summary', label: 'Overall comments', type: 'textarea' },
  ], rowTitle: 'Evaluation scorecard', columns: [{ key: 'parameter', label: 'Parameter' }, { key: 'weight', label: 'Weight %', type: 'number' }, { key: 'score', label: 'Score / 5', type: 'number' }, { key: 'comments', label: 'Evidence / comments' }] },
}

function esc(value: unknown) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character] ?? character) }
function csvValue(value: unknown) { return `"${String(value ?? '').replaceAll('"', '""')}"` }
function downloadCsv(filename: string, headers: string[], rows: unknown[][]) { const blob = new Blob([[headers, ...rows].map((row) => row.map(csvValue).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = filename; link.click(); URL.revokeObjectURL(url) }
function openBlob(blob: Blob) { const url = URL.createObjectURL(blob); window.open(url, '_blank', 'noopener,noreferrer'); window.setTimeout(() => URL.revokeObjectURL(url), 60_000) }

function printReport(config: ToolConfig, fields: Record<string, string>, rows: Record<string, string>[]) {
  const popup = window.open('', '_blank', 'width=960,height=800'); if (!popup) return
  const letter = config.title.startsWith('Offer')
  const body = letter ? `<p>${esc(fields.date)}</p><p>To,<br><strong>${esc(fields.employee)}</strong><br>${esc(fields.address).replaceAll('\n', '<br>')}</p><h2>${esc(fields.letter_type || 'Employment Letter')}</h2><p>Dear ${esc(fields.employee)},</p><p>We are pleased to ${fields.letter_type === 'Appointment Letter' ? 'appoint' : 'offer'} you the position of <strong>${esc(fields.designation)}</strong> in the <strong>${esc(fields.department)}</strong> department at AROMAZEN. Your joining date will be ${esc(fields.joining)}, your work location will be ${esc(fields.location)}, and you will report to ${esc(fields.reporting)}.</p><p>Your compensation will be ${esc(fields.salary)}. The probation period will be ${esc(fields.probation)}.</p><p>${esc(fields.terms).replaceAll('\n', '<br>')}</p><p>For AROMAZEN<br><br><strong>${esc(fields.signatory)}</strong><br>Authorized Signatory</p>` : `<div class="grid">${config.fields.map((field) => `<div><small>${esc(field.label)}</small><strong>${esc(fields[field.key])}</strong></div>`).join('')}</div>`
  const table = rows.length ? `<h3>${esc(config.rowTitle)}</h3><table><thead><tr>${config.columns.map((column) => `<th>${esc(column.label)}</th>`).join('')}</tr></thead><tbody>${rows.map((row) => `<tr>${config.columns.map((column) => `<td>${esc(row[column.key])}</td>`).join('')}</tr>`).join('')}</tbody></table>` : ''
  popup.document.write(`<!doctype html><html><head><title>${esc(config.title)}</title><style>body{font:14px Arial;max-width:900px;margin:36px auto;color:#111;line-height:1.6}h1{border-bottom:2px solid #111;padding-bottom:10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.grid div{border:1px solid #ddd;padding:10px}.grid small,.grid strong{display:block}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{border:1px solid #bbb;padding:8px;text-align:left}@media print{body{margin:12mm}}</style></head><body><h1>AROMAZEN</h1><h2>${esc(config.title)}</h2>${body}${table}</body></html>`); popup.document.close(); popup.focus(); popup.print()
}

function StructuredTool({ config }: { config: ToolConfig }) {
  const [fields, setFields] = useState<Record<string, string>>(() => Object.fromEntries(config.fields.map((field) => [field.key, field.type === 'date' ? new Date().toISOString().slice(0, 10) : field.options?.[0] ?? ''])))
  const [rows, setRows] = useState<Record<string, string>[]>([Object.fromEntries(config.columns.map((column) => [column.key, column.options?.[0] ?? '']))])
  const completed = config.fields.filter((field) => fields[field.key]?.trim()).length
  function input(field: Field, value: string, change: (value: string) => void) { if (field.type === 'textarea') return <textarea rows={3} value={value} onChange={(event) => change(event.target.value)} className="w-full rounded-xl border border-border bg-background p-3 text-sm" />; if (field.type === 'select') return <select value={value} onChange={(event) => change(event.target.value)} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm">{field.options?.map((option) => <option key={option}>{option}</option>)}</select>; return <input type={field.type ?? 'text'} value={value} placeholder={field.placeholder} onChange={(event) => change(event.target.value)} className="h-11 w-full rounded-xl border border-border bg-background px-3 text-sm" /> }
  return <main className="space-y-5 p-4 md:p-6"><PageHeader title={config.title} description={config.description} /><section className="rounded-2xl border border-border bg-card p-4 md:p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Document details</h2><p className="text-xs text-muted-foreground">{completed} of {config.fields.length} details completed</p></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs text-primary">Structured form</span></div><div className="grid gap-4 md:grid-cols-2">{config.fields.map((field) => <label key={field.key} className={field.type === 'textarea' ? 'md:col-span-2' : ''}><span className="mb-1.5 block text-xs text-muted-foreground">{field.label}</span>{input(field, fields[field.key] ?? '', (value) => setFields((current) => ({ ...current, [field.key]: value })))}</label>)}</div></section><section className="rounded-2xl border border-border bg-card p-4 md:p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">{config.rowTitle}</h2><p className="text-xs text-muted-foreground">Add or remove rows as needed.</p></div><Button variant="outline" onClick={() => setRows((current) => [...current, Object.fromEntries(config.columns.map((column) => [column.key, column.options?.[0] ?? '']))])}><Plus className="mr-2 h-4 w-4" />Add row</Button></div><div className="mt-4 space-y-3">{rows.map((row, index) => <div key={index} className="grid gap-2 rounded-xl border border-border p-3 md:grid-cols-2 xl:grid-cols-5">{config.columns.map((column) => <label key={column.key}><span className="mb-1 block text-[11px] text-muted-foreground">{column.label}</span>{input(column, row[column.key] ?? '', (value) => setRows((current) => current.map((item, rowIndex) => rowIndex === index ? { ...item, [column.key]: value } : item)))}</label>)}<button type="button" onClick={() => setRows((current) => current.filter((_, rowIndex) => rowIndex !== index))} className="flex items-center gap-1 self-end p-2 text-xs text-destructive"><Trash2 className="h-4 w-4" />Remove</button></div>)}</div></section><section className="flex flex-wrap justify-end gap-2 rounded-2xl border border-border bg-card p-4"><Button variant="outline" onClick={() => downloadCsv(`${config.title.replaceAll(' ', '-').toLowerCase()}.csv`, [...config.fields.map((field) => field.label), ...config.columns.map((column) => column.label)], [[...config.fields.map((field) => fields[field.key]), ...config.columns.map(() => '')], ...rows.map((row) => [...config.fields.map(() => ''), ...config.columns.map((column) => row[column.key])])])}><Download className="mr-2 h-4 w-4" />Download data</Button><Button onClick={() => printReport(config, fields, rows)}><Printer className="mr-2 h-4 w-4" />Review / Print PDF</Button></section></main>
}

const DEFAULT_ATTENDANCE_SHIFTS: AttendanceShiftRule[] = [
  { name: 'Shift 1', start: '06:00', end: '14:00', grace_minutes: 0 },
  { name: 'General', start: '09:00', end: '17:30', grace_minutes: 0 },
  { name: 'Shift 2', start: '14:00', end: '22:00', grace_minutes: 0 },
  { name: 'Shift 3', start: '22:00', end: '06:00', grace_minutes: 0 },
]

function AttendanceExceptionQueue({ result, filter, onFilter }: { result: AttendanceAnalysis; filter: string; onFilter: (value: string) => void }) {
  const records = result.records.filter((item) => { const missingPunch = item.status !== 'Absent' && item.status !== 'Weekly off' && (!item.first_in || !item.last_out); const hasException = (item.status_code !== 'P' && item.status_code !== 'WO') || missingPunch; if (!hasException) return false; if (filter === 'All') return true; if (filter === 'Missing punch') return missingPunch; return item.status === filter })
  const tone = (status: string) => status === 'Absent' ? 'text-red-400' : 'text-amber-400'
  return <section className="rounded-2xl border border-amber-500/25 bg-card p-4 md:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-amber-500">Action queue</p><h2 className="mt-1 font-semibold">Attendance exceptions needing review</h2><p className="mt-1 text-xs text-muted-foreground">Focus on irregular records instead of checking every employee-day.</p></div><Button size="sm" variant="outline" disabled={records.length === 0} onClick={() => downloadCsv('attendance-exceptions-action-sheet.csv', ['Employee code', 'Employee', 'Department', 'Date', 'Shift', 'Clock in', 'Clock out', 'Hours', 'Status', 'Action / remarks'], records.map((item) => [item.employee_code, item.employee_name, item.department, item.date, item.shift_name, item.first_in, item.last_out, item.worked_hours, item.status, '']))}><Download className="mr-2 h-4 w-4" />Download action sheet</Button></div><div className="mt-4 flex flex-wrap gap-2">{['All', 'Absent', 'Late', 'Early leave', 'Half day', 'Missing punch'].map((item) => <button type="button" key={item} onClick={() => onFilter(item)} className={`rounded-full px-3 py-1.5 text-xs ${filter === item ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:text-foreground'}`}>{item}</button>)}</div><div className="mt-4 max-h-[28rem] overflow-auto rounded-xl border border-border"><table className="w-full min-w-[900px] text-sm"><thead className="sticky top-0 bg-card text-xs text-muted-foreground"><tr><th className="p-3 text-left">Employee</th><th>Department</th><th>Date</th><th>Shift</th><th>Clock in</th><th>Clock out</th><th>Hours</th><th>Status</th></tr></thead><tbody>{records.map((item, index) => { const missingPunch = item.status !== 'Absent' && item.status !== 'Weekly off' && (!item.first_in || !item.last_out); return <tr key={`${item.employee_code}-${item.date}-${index}`} className="border-t border-border"><td className="p-3"><p className="font-medium">{item.employee_name}</p><p className="text-xs text-muted-foreground">{item.employee_code || 'No ID'}</p></td><td className="text-center">{item.department}</td><td className="text-center">{item.date}</td><td className="text-center">{item.shift_name}</td><td className="text-center">{item.first_in || 'Missing'}</td><td className="text-center">{item.last_out || 'Missing'}</td><td className="text-center">{item.worked_hours}</td><td className={`text-center font-medium ${tone(item.status)}`}>{missingPunch ? `${item.status} · missing punch` : item.status}</td></tr>})}{records.length === 0 && <tr><td colSpan={8} className="p-8 text-center text-sm text-muted-foreground">No records match this exception filter.</td></tr>}</tbody></table></div></section>
}

function AttendanceTool() {
  const { accessToken } = useAuth(); const { notify } = useToast(); const fileRef = useRef<HTMLInputElement>(null); const shiftRosterRef = useRef<HTMLInputElement>(null)
  const [file, setFile] = useState<File | null>(null); const [shiftRoster, setShiftRoster] = useState<File | null>(null); const [shifts, setShifts] = useState<AttendanceShiftRule[]>(DEFAULT_ATTENDANCE_SHIFTS); const [busy, setBusy] = useState(false); const [result, setResult] = useState<AttendanceAnalysis | null>(null)
  const [shiftFilter, setShiftFilter] = useState('All'); const [recordSearch, setRecordSearch] = useState(''); const [exceptionFilter, setExceptionFilter] = useState('All'); const [hrRules, setHrRules] = useState<{ collection: KnowledgeCollection; document: KnowledgeDocument }[]>([])
  useEffect(() => { if (!accessToken) return; void api.knowledge.collections(accessToken).then(async (collections) => { const hrCollections = collections.filter((item) => item.slug === 'hr' || item.slug === 'human-resources' || item.name.toLowerCase().includes('hr')); const groups = await Promise.all(hrCollections.map(async (collection) => (await api.knowledge.documents(accessToken, collection.id)).filter((document) => ['attendance_rule', 'leave_rule', 'hr_policy'].includes(document.document_category ?? '') || /attendance|leave|policy|rule/i.test(document.name)).map((document) => ({ collection, document })))); setHrRules(groups.flat()) }).catch(() => undefined) }, [accessToken])
  const shownRecords = useMemo(() => result?.records.filter((item) => (shiftFilter === 'All' || item.shift_name === shiftFilter) && `${item.employee_name} ${item.employee_code} ${item.department}`.toLowerCase().includes(recordSearch.toLowerCase())) ?? [], [result, shiftFilter, recordSearch])
  function updateShift(index: number, key: keyof AttendanceShiftRule, value: string) { setShifts((current) => current.map((item, rowIndex) => rowIndex === index ? { ...item, [key]: key === 'grace_minutes' ? Math.max(0, Number(value) || 0) : value } : item)); setResult(null) }
  function downloadShiftRosterTemplate() { const rows = result ? result.employees.map((item) => [item.employee_code, item.employee_name, '', '', '', 'Duplicate the employee row for every continuous shift period.']) : [['', '', '', '', '', 'Add one row per continuous shift period.']]; downloadCsv('attendance-shift-roster-template.csv', ['Employee ID', 'Employee Name', 'From Date (YYYY-MM-DD)', 'To Date (YYYY-MM-DD)', 'Shift Name', 'Instructions'], rows) }
  async function analyze() { if (!accessToken || !file || shifts.length === 0) return; setBusy(true); try { setResult(await api.payroll.analyzeAttendance(accessToken, file, shifts, shiftRoster)); notify('success', 'Complete attendance and shift analysis is ready.') } catch (error) { notify('error', error instanceof ApiError ? error.message : 'Unable to analyze attendance.') } finally { setBusy(false) } }
  async function openRule(item: { collection: KnowledgeCollection; document: KnowledgeDocument }) { if (!accessToken) return; const response = await fetch(api.knowledge.documentContentUrl(item.collection.id, item.document.id), { headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) return notify('error', 'Unable to open this HR rule.'); openBlob(await response.blob()) }
  const statusTone = (status: string) => status === 'Present' ? 'text-emerald-400' : status === 'Weekly off' ? 'text-sky-400' : status === 'Absent' ? 'text-red-400' : 'text-amber-400'
  return <main className="space-y-5 p-4 md:p-6"><PageHeader title="Smart Attendance Management" description="Upload the fingerprint monthly status report, review only exceptions, and use approved HR rules while taking action." />
    {hrRules.length > 0 && <details className="rounded-2xl border border-border bg-card"><summary className="cursor-pointer p-4 text-sm font-medium">Approved attendance and leave rules from Knowledge ({hrRules.length})</summary><div className="grid gap-2 border-t border-border p-4 sm:grid-cols-2 xl:grid-cols-3">{hrRules.map((item) => <button type="button" key={item.document.id} onClick={() => void openRule(item)} className="flex items-center gap-3 rounded-xl border border-border p-3 text-left hover:border-primary/40"><FileText className="h-4 w-4 shrink-0 text-primary" /><span className="min-w-0"><span className="block truncate text-sm font-medium">{item.document.name}</span><span className="block text-xs text-muted-foreground">{item.document.document_category?.replaceAll('_', ' ') || item.collection.name}</span></span></button>)}</div></details>}
    {result && <AttendanceExceptionQueue result={result} filter={exceptionFilter} onFilter={setExceptionFilter} />}
    <section className="rounded-2xl border border-border bg-card p-4 md:p-5"><div className="grid gap-3 lg:grid-cols-[1fr_1fr_auto]"><label><span className="mb-1.5 block text-xs text-muted-foreground">Fingerprint monthly attendance Excel</span><button type="button" onClick={() => fileRef.current?.click()} className="flex h-11 w-full items-center rounded-xl border border-dashed border-border px-3 text-sm"><FileSpreadsheet className="mr-2 h-4 w-4 text-emerald-400" />{file?.name ?? 'Choose .xlsx monthly status report'}</button><input ref={fileRef} hidden type="file" accept=".xlsx,.xlsm" onChange={(event: ChangeEvent<HTMLInputElement>) => { setFile(event.target.files?.[0] ?? null); setResult(null) }} /></label><label><span className="mb-1.5 block text-xs text-muted-foreground">Shift roster override (optional)</span><button type="button" onClick={() => shiftRosterRef.current?.click()} className="flex h-11 w-full items-center rounded-xl border border-dashed border-border px-3 text-sm"><FileSpreadsheet className="mr-2 h-4 w-4 text-sky-400" />{shiftRoster?.name ?? 'Choose shift roster .xlsx or .csv'}</button><input ref={shiftRosterRef} hidden type="file" accept=".xlsx,.xlsm,.csv" onChange={(event: ChangeEvent<HTMLInputElement>) => { setShiftRoster(event.target.files?.[0] ?? null); setResult(null) }} /></label><Button className="self-end" disabled={!file || busy || shifts.length === 0} onClick={() => void analyze()}>{busy ? <LoaderCircle className="mr-2 h-4 w-4 animate-spin" /> : <CheckCircle2 className="mr-2 h-4 w-4" />}{busy ? 'Analyzing complete month' : 'Analyze attendance'}</Button></div><div className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-muted/30 p-3"><p className="max-w-3xl text-xs leading-5 text-muted-foreground">For changing shifts, use one roster row per continuous date range. Example: Person A · 1–10 July · Shift 2, then another row for 11–31 July · Shift 1. Roster assignments override automatic clock-in matching.</p><Button size="sm" variant="outline" onClick={downloadShiftRosterTemplate}><Download className="mr-2 h-4 w-4" />Download shift roster template</Button></div>
      <details className="mt-4 rounded-xl border border-border"><summary className="cursor-pointer p-3 text-sm font-medium">Shift definitions and late grace</summary><div className="space-y-3 border-t border-border p-3"><p className="text-xs leading-5 text-muted-foreground">Late grace is applied to the configured shift start time. The optional roster controls shift changes by employee and date range; days without a roster entry are assigned automatically from clock-in time.</p>{shifts.map((shift, index) => <div key={`${shift.name}-${index}`} className="grid gap-2 rounded-xl bg-muted/30 p-3 sm:grid-cols-[1.2fr_1fr_1fr_1fr_auto]"><label><span className="mb-1 block text-[11px] text-muted-foreground">Shift name</span><input value={shift.name} onChange={(event) => updateShift(index, 'name', event.target.value)} className="h-9 w-full rounded-lg border border-border bg-background px-2 text-sm" /></label><label><span className="mb-1 block text-[11px] text-muted-foreground">Start</span><input type="time" value={shift.start} onChange={(event) => updateShift(index, 'start', event.target.value)} className="h-9 w-full rounded-lg border border-border bg-background px-2 text-sm" /></label><label><span className="mb-1 block text-[11px] text-muted-foreground">End</span><input type="time" value={shift.end} onChange={(event) => updateShift(index, 'end', event.target.value)} className="h-9 w-full rounded-lg border border-border bg-background px-2 text-sm" /></label><label><span className="mb-1 block text-[11px] text-muted-foreground">Late grace (minutes)</span><input type="number" min="0" value={shift.grace_minutes} onChange={(event) => updateShift(index, 'grace_minutes', event.target.value)} className="h-9 w-full rounded-lg border border-border bg-background px-2 text-sm" /></label><button type="button" onClick={() => { setShifts((current) => current.filter((_, rowIndex) => rowIndex !== index)); setResult(null) }} className="self-end p-2 text-destructive"><Trash2 className="h-4 w-4" /></button></div>)}<Button size="sm" variant="outline" onClick={() => { setShifts((current) => [...current, { name: `Shift ${current.length + 1}`, start: '09:00', end: '17:30', grace_minutes: 0 }]); setResult(null) }}><Plus className="mr-2 h-4 w-4" />Add shift</Button></div></details>
    </section>
    {result && <><section className="rounded-2xl border border-primary/20 bg-primary/5 p-4"><p className="text-sm font-medium">Analysis period: {result.period.from} to {result.period.to}</p><p className="mt-1 text-xs text-muted-foreground">{result.filename} · {result.record_count} daily employee records recognized · {result.roster_assigned_records} roster-assigned · {result.automatic_assigned_records} automatically assigned</p></section>
      <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold">{result.employee_count}</p><p className="text-xs text-muted-foreground">Employees</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold text-emerald-400">{result.present_days}</p><p className="text-xs text-muted-foreground">Present employee-days</p><p className="mt-1 text-[11px] text-muted-foreground">{result.employee_count} employees × {(result.present_days / Math.max(result.employee_count, 1)).toFixed(1)} average present days</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold text-red-400">{result.absent_days}</p><p className="text-xs text-muted-foreground">Absent days</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold text-amber-400">{result.late_days}</p><p className="text-xs text-muted-foreground">Late days</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold text-amber-400">{result.early_leave_days}</p><p className="text-xs text-muted-foreground">Early leaves</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold">{result.weekly_off_days}</p><p className="text-xs text-muted-foreground">Weekly offs</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold">{result.total_hours.toFixed(1)}</p><p className="text-xs text-muted-foreground">Total working hours</p></div><div className="rounded-2xl border border-border bg-card p-4"><p className="text-2xl font-semibold">{result.overtime_hours.toFixed(1)}</p><p className="text-xs text-muted-foreground">Overtime hours</p></div></section>
      <details className="rounded-2xl border border-border bg-card"><summary className="cursor-pointer p-4 text-sm font-medium">Detailed reports and exports</summary><div className="space-y-5 border-t border-border p-4">
      <section className="rounded-2xl border border-border bg-card p-4 md:p-5"><h2 className="font-semibold">Shift-wise analysis</h2><p className="mt-1 text-xs text-muted-foreground">Shift is assigned separately for every employee-day. Uploaded roster ranges take priority; remaining days use clock-in matching.</p><div className="mt-4 overflow-auto"><table className="w-full min-w-[850px] text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="p-3 text-left">Shift</th><th>Employees</th><th>Scheduled</th><th>Present</th><th>Absent</th><th>Late</th><th>Early leave</th><th>Avg hours</th><th>Attendance</th></tr></thead><tbody>{result.shifts.map((item) => <tr key={item.name} className="border-t border-border"><td className="p-3 font-medium">{item.name}</td><td className="text-center">{item.employee_count}</td><td className="text-center">{item.scheduled_days}</td><td className="text-center">{item.present_days}</td><td className="text-center">{item.absent_days}</td><td className="text-center">{item.late_days}</td><td className="text-center">{item.early_leave_days}</td><td className="text-center">{item.average_hours}</td><td className="text-center font-medium">{item.attendance_rate}%</td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border border-border bg-card p-4 md:p-5"><h2 className="font-semibold">Department-wise analysis</h2><div className="mt-4 overflow-auto"><table className="w-full min-w-[760px] text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="p-3 text-left">Department</th><th>Employees</th><th>Present</th><th>Absent</th><th>Late</th><th>Total hours</th><th>Attendance</th></tr></thead><tbody>{result.departments.map((item) => <tr key={item.name} className="border-t border-border"><td className="p-3 font-medium">{item.name}</td><td className="text-center">{item.employee_count}</td><td className="text-center">{item.present_days}</td><td className="text-center">{item.absent_days}</td><td className="text-center">{item.late_days}</td><td className="text-center">{item.total_hours}</td><td className="text-center font-medium">{item.attendance_rate}%</td></tr>)}</tbody></table></div></section>
      <section className="rounded-2xl border border-border bg-card p-4 md:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">Complete employee summary</h2><p className="text-xs text-muted-foreground">Primary shift, attendance exceptions and working-hour totals.</p></div><Button size="sm" variant="outline" onClick={() => downloadCsv('attendance-employee-summary.csv', ['Employee code', 'Employee', 'Department', 'Primary shift', 'Scheduled days', 'Present days', 'Absent days', 'Weekly offs', 'Late days', 'Early leaves', 'Half days', 'Total hours', 'Overtime hours', 'Average hours', 'Attendance rate %'], result.employees.map((item) => [item.employee_code, item.employee_name, item.department, item.primary_shift, item.scheduled_days, item.present_days, item.absent_days, item.weekly_off_days, item.late_days, item.early_leave_days, item.half_days, item.total_hours, item.overtime_hours, item.average_hours, item.attendance_rate]))}><Download className="mr-2 h-4 w-4" />Download summary</Button></div><div className="mt-4 overflow-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="p-3 text-left">Employee</th><th>Department</th><th>Primary shift</th><th>Present / scheduled</th><th>Absent</th><th>Late</th><th>Early leave</th><th>Total hours</th><th>OT hours</th><th>Attendance</th></tr></thead><tbody>{result.employees.map((item) => <tr key={item.employee_code || item.employee_name} className="border-t border-border"><td className="p-3"><p className="font-medium">{item.employee_name}</p><p className="text-xs text-muted-foreground">ID: {item.employee_code || '—'}</p></td><td className="text-center">{item.department}</td><td className="text-center">{item.primary_shift}</td><td className="text-center">{item.present_days} / {item.scheduled_days}</td><td className="text-center">{item.absent_days}</td><td className="text-center">{item.late_days}</td><td className="text-center">{item.early_leave_days}</td><td className="text-center">{item.total_hours}</td><td className="text-center">{item.overtime_hours}</td><td className="text-center font-medium">{item.attendance_rate}%</td></tr>)}</tbody></table></div></section>
      <details className="rounded-2xl border border-border bg-card"><summary className="cursor-pointer p-4 font-medium">Complete daily attendance ({result.records.length})</summary><div className="border-t border-border p-4"><div className="grid gap-3 sm:grid-cols-[1fr_14rem]"><input value={recordSearch} onChange={(event) => setRecordSearch(event.target.value)} placeholder="Search employee, ID or department" className="h-10 rounded-xl border border-border bg-background px-3 text-sm" /><select value={shiftFilter} onChange={(event) => setShiftFilter(event.target.value)} className="h-10 rounded-xl border border-border bg-background px-3 text-sm"><option>All</option>{result.shifts.map((item) => <option key={item.name}>{item.name}</option>)}</select></div></div><div className="max-h-[36rem] overflow-auto border-t border-border"><table className="w-full min-w-[1080px] text-sm"><thead className="sticky top-0 bg-card"><tr><th className="p-3 text-left">Employee</th><th>Department</th><th>Date</th><th>Shift</th><th>Assigned by</th><th>Clock in</th><th>Clock out</th><th>Hours</th><th>OT</th><th>Status</th></tr></thead><tbody>{shownRecords.map((item, index) => <tr key={`${item.employee_code}-${item.date}-${index}`} className="border-t border-border"><td className="p-3">{item.employee_name}</td><td className="text-center">{item.department}</td><td className="text-center">{item.date}</td><td className="text-center">{item.shift_name}</td><td className="text-center text-xs text-muted-foreground">{item.assignment_source}</td><td className="text-center">{item.first_in || '—'}</td><td className="text-center">{item.last_out || '—'}</td><td className="text-center">{item.worked_hours}</td><td className="text-center">{item.overtime_hours}</td><td className={`text-center font-medium ${statusTone(item.status)}`}>{item.status}</td></tr>)}</tbody></table></div></details>
      </div></details>
    </>}</main>
}

function SopTool() {
  const { accessToken } = useAuth(); const { notify } = useToast(); const [collection, setCollection] = useState<KnowledgeCollection | null>(null); const [documents, setDocuments] = useState<KnowledgeDocument[]>([]); const [query, setQuery] = useState(''); const [loading, setLoading] = useState(true)
  useEffect(() => { if (!accessToken) return; void api.knowledge.collections(accessToken).then((items) => { const target = items.find((item) => item.name === 'R&D' || item.slug === 'r-d' || item.name.includes('R&D')); setCollection(target ?? null); if (target) return api.knowledge.documents(accessToken, target.id).then(setDocuments) }).catch((error) => notify('error', error instanceof ApiError ? error.message : 'Unable to load R&D SOPs.')).finally(() => setLoading(false)) }, [accessToken, notify])
  const shown = useMemo(() => documents.filter((document) => document.name.toLowerCase().includes(query.toLowerCase()) && /sop|procedure|instruction/i.test(document.name)), [documents, query])
  async function open(document: KnowledgeDocument) { if (!accessToken || !collection) return; const response = await fetch(api.knowledge.documentContentUrl(collection.id, document.id), { headers: { Authorization: `Bearer ${accessToken}` } }); if (!response.ok) return notify('error', 'Unable to open this SOP.'); openBlob(await response.blob()) }
  return <main className="space-y-5 p-4 md:p-6"><PageHeader title="SOPs to be Followed" description="Find and open approved procedures from the R&D knowledge collection." /><section className="rounded-2xl border border-border bg-card p-4"><div className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search SOP name…" className="h-11 w-full rounded-xl border border-border bg-background pl-10 pr-3 text-sm" /></div></section><section className="rounded-2xl border border-border bg-card p-4 md:p-5">{loading ? <p className="text-sm text-muted-foreground">Loading approved SOPs…</p> : shown.length === 0 ? <div className="py-12 text-center"><BookOpenCheck className="mx-auto h-9 w-9 text-muted-foreground" /><p className="mt-3 font-medium">No matching SOPs found</p><p className="mt-1 text-sm text-muted-foreground">Upload approved SOP files to the R&D knowledge collection first.</p></div> : <div className="grid gap-3 md:grid-cols-2">{shown.map((document) => <button key={document.id} onClick={() => void open(document)} className="flex items-center justify-between rounded-xl border border-border p-4 text-left hover:border-primary/50"><div className="flex min-w-0 items-center gap-3"><FileText className="h-5 w-5 shrink-0 text-primary" /><div className="min-w-0"><p className="truncate text-sm font-medium">{document.name}</p><p className="text-xs text-muted-foreground">Version {document.version} · {document.status}</p></div></div><Eye className="h-4 w-4 text-muted-foreground" /></button>)}</div>}</section></main>
}

export default function DepartmentToolPage() {
  const { tool } = useParams<{ tool: string }>(); const { user } = useAuth(); const config = CONFIGS[tool]
  const isQaTool = tool.startsWith('qa-'); const isRegulatoryTool = tool.startsWith('regulatory-'); const requiredDepartment = isQaTool ? 'Quality Assurance' : isRegulatoryTool ? 'Regulatory' : tool.startsWith('rnd-') ? 'R&D' : 'HR'; const canUse = (isQaTool ? ['QA', 'QA & QC', 'Quality Assurance'].includes(user?.department_name ?? '') : isRegulatoryTool ? ['Regulatory', 'Regulatory Affairs'].includes(user?.department_name ?? '') : tool.startsWith('rnd-') ? user?.department_name === 'R&D' : ['HR', 'Human Resources'].includes(user?.department_name ?? '')) || user?.role_names.some((role) => role === 'Super Admin' || role === 'Admin')
  if (!canUse) return <AppLayout><main className="grid min-h-[70vh] place-items-center p-6"><div className="text-center"><h1 className="text-xl font-semibold">Access restricted</h1><p className="mt-2 text-sm text-muted-foreground">This workspace is available only to {requiredDepartment}.</p></div></main></AppLayout>
  return <AppLayout>{tool === 'qa-coa' ? <QaCoaTool /> : tool === 'regulatory-documents' ? <RegulatoryDocumentsTool /> : tool === 'hr-letters' ? <HrLettersTool /> : tool === 'hr-custom-letters' ? <HrCustomLettersTool /> : tool === 'hr-interview' ? <HrInterviewTool /> : tool === 'hr-attendance' ? <AttendanceTool /> : tool === 'rnd-sops' ? <SopTool /> : config ? <StructuredTool config={config} /> : <main className="p-6">Tool not found.</main>}</AppLayout>
}
